name: teki_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  card_slider: ^1.0.5
  carousel_slider: ^5.0.0
  cherry_toast: ^1.8.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  expansion_tile_card: ^3.0.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_easy_faq: ^1.0.1
  flutter_hooks: ^0.21.2
  flutter_onboarding_slider: ^1.0.11
  flutter_riverpod: ^2.6.1
  flutter_rounded_date_picker: ^3.0.4
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  pdf: ^3.10.8
  printing: ^5.12.0
  reactive_forms: ^18.0.0
  shared_preferences: ^2.5.3
  sidebarx: ^0.17.1
  url_launcher: ^6.3.1
  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/logo/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/images/gif/
    - assets/icons/icon_image/
    - assets/images/avatar/
    - assets/icons/icon_svg/
    - assets/images/offer/
    - assets/images/products/
    - assets/images/other/
    - assets/images/logo/icon.png
    - .env
