name: teki_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.20+15

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1
  card_slider: ^1.0.5
  carousel_slider: ^5.0.0
  cherry_toast: ^1.8.0
  toastification: ^3.0.3
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  expansion_tile_card: ^3.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_easy_faq: ^1.0.1
  flutter_hooks: ^0.21.2
  flutter_onboarding_slider: ^1.0.11
  flutter_riverpod: ^2.6.1
  flutter_rounded_date_picker: ^3.0.4
  flutter_slidable: ^4.0.1
  flutter_svg: ^2.0.9
  flutter_switch: ^0.3.2
  get: ^4.6.6
  google_fonts: ^8.0.2
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  mobile_scanner: ^7.2.0
  path_provider: ^2.1.2
  pdf: ^3.10.8
  printing: ^5.12.0
  reactive_forms: ^18.0.0
  shared_preferences: ^2.5.3
  sidebarx: ^0.17.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  syncfusion_flutter_pdfviewer: ^30.1.40
  socket_io_client: ^2.0.3+1
  uuid: ^4.5.1
  confetti: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/logo/icon_no_alpha.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/images/gif/
    - assets/icons/icon_image/
    - assets/icons/icon_svg/
    - assets/images/avatar/
    - assets/images/offer/
    - assets/images/products/
    - assets/images/other/
    - assets/images/payment/
    - assets/images/logo/icon.png
    - .env
    - .env.production
